name: Roundcube docker image

on: [push]
       
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login, build and push
        env: 
          DOCKER_HUB_USER: windsource
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          # Create new builder
          docker buildx create --name mybuilder --driver docker-container --bootstrap
          # Use new builder
          docker buildx use mybuilder
          # Build and push
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/windsource/roundcube:$(cat VERSION) --push .